function foRebuildPortfolioState() {
  const module = 'PortfolioStateService';

  try {
    foInfo_(module, 'Start', 'Portfolio State rebuild started.');

    const dashboard = foDashboard_();

    const source = dashboard.getSheetByName(FO_SHEETS.PORTFOLIO_MASTER);

    const state = foEnsureSheet_(dashboard, 'Portfolio State', [
      'Timestamp',
      'Position ID',
      'Ticker',
      'Company',
      'Account',
      'Quantity',
      'Current Price',
      'Market Value',
      'Weight',
      'Target Weight',
      'Drift',
      'Status',
      'Notes'
    ]);

    if (!source) {
      throw new Error('Portfolio Master worksheet not found.');
    }

    const values = source.getDataRange().getValues();

    if (values.length < 2) {
      foWarn_(module, 'No Data', 'Portfolio Master has no data rows.');
      return {
        status: 'NO_DATA',
        rowsWritten: 0
      };
    }

    const headers = values[0].map(String);

    const rows = [];
    let totalMarketValue = 0;

    for (let r = 1; r < values.length; r++) {
      const row = values[r];

      const positionId = foGetVal_(row, headers, 'Position ID');
      const ticker = foGetVal_(row, headers, 'Ticker');

      if (!ticker) continue;

      const company = foGetVal_(row, headers, 'Company');
      const account = foGetVal_(row, headers, 'Account');
      const quantity = foNum_(foGetVal_(row, headers, 'Quantity'));
      const currentPrice = foNum_(foGetVal_(row, headers, 'Current Price'));
      const marketValue = foNum_(foGetVal_(row, headers, 'Market Value'));
      const targetWeight = foNum_(foGetVal_(row, headers, 'Target Weight'));

      const resolvedMarketValue =
        marketValue !== ''
          ? marketValue
          : quantity !== '' && currentPrice !== ''
            ? quantity * currentPrice
            : '';

      if (resolvedMarketValue !== '') {
        totalMarketValue += Number(resolvedMarketValue);
      }

      rows.push({
        positionId: positionId,
        ticker: ticker,
        company: company,
        account: account,
        quantity: quantity,
        currentPrice: currentPrice,
        marketValue: resolvedMarketValue,
        targetWeight: targetWeight
      });
    }

    if (state.getLastRow() > 1) {
      state.getRange(2, 1, state.getLastRow() - 1, 13).clearContent();
    }

    const output = rows.map(function (item) {
      const weight =
        totalMarketValue > 0 && item.marketValue !== ''
          ? Number(item.marketValue) / totalMarketValue
          : '';

      const drift =
        weight !== '' && item.targetWeight !== ''
          ? weight - Number(item.targetWeight)
          : '';

      return [
        new Date(),
        item.positionId,
        item.ticker,
        item.company,
        item.account,
        item.quantity,
        item.currentPrice,
        item.marketValue,
        weight,
        item.targetWeight,
        drift,
        'Active',
        'Generated by PortfolioStateService'
      ];
    });

    if (output.length > 0) {
      state.getRange(2, 1, output.length, 13).setValues(output);
    }

    foInfo_(
      module,
      'Complete',
      output.length + ' Portfolio State rows rebuilt.'
    );

    return {
      status: 'SUCCESS',
      rowsWritten: output.length
    };

  } catch (error) {
    foError_(module, 'Failure', error);
    throw error;
  }
}