function foAppendRecommendationEvent(event) {
  const module = 'RecommendationService';

  try {
    foInfo_(module, 'Start', 'Appending recommendation event.');

    const sheet = foEnsureSheet_(foDashboard_(), FO_SHEETS.RECOMMENDATION_LEDGER, [
      'Recommendation ID',
      'Parent Recommendation ID',
      'Event ID',
      'Recommendation Date',
      'Recommendation Time',
      'Recommendation Source',
      'Generated By',
      'Ticker',
      'Company',
      'Asset Class',
      'Sector',
      'Investment Theme',
      'Recommendation Type',
      'Recommendation Action',
      'Recommendation Status',
      'Priority',
      'Materiality Score',
      'Confidence Score',
      'Entry Price',
      'Buy Zone Low',
      'Buy Zone High',
      'Target Price',
      'Stop Loss',
      'Time Horizon',
      'Suggested Allocation %',
      'Portfolio Account',
      'Decision Status',
      'Decision Date',
      'Execution Status',
      'Related Transaction ID',
      'Risk Rating',
      'Expected Alpha',
      'Benchmark',
      'Investment Thesis',
      'Supporting Evidence',
      'Assumptions',
      'Risks',
      'CIO Notes',
      'Created Date',
      'Last Updated'
    ]);

    const recommendationId =
      event.recommendationId || foNowId_('REC');

    const eventId =
      event.eventId || foNowId_('EVT');

    sheet.appendRow([
      recommendationId,
      event.parentRecommendationId || '',
      eventId,
      event.recommendationDate || new Date(),
      event.recommendationTime || new Date(),
      event.recommendationSource || 'Apps Script',
      event.generatedBy || foGetActiveUser_(),
      event.ticker || '',
      event.company || '',
      event.assetClass || '',
      event.sector || '',
      event.investmentTheme || '',
      event.recommendationType || 'Initial',
      event.recommendationAction || 'Watch',
      event.recommendationStatus || 'Proposed',
      event.priority || '',
      event.materialityScore || '',
      event.confidenceScore || '',
      event.entryPrice || '',
      event.buyZoneLow || '',
      event.buyZoneHigh || '',
      event.targetPrice || '',
      event.stopLoss || '',
      event.timeHorizon || '',
      event.suggestedAllocation || '',
      event.portfolioAccount || '',
      event.decisionStatus || 'Pending',
      event.decisionDate || '',
      event.executionStatus || 'Not Executed',
      event.relatedTransactionId || '',
      event.riskRating || '',
      event.expectedAlpha || '',
      event.benchmark || '',
      event.investmentThesis || '',
      event.supportingEvidence || '',
      event.assumptions || '',
      event.risks || '',
      event.cioNotes || '',
      new Date(),
      new Date()
    ]);

    foInfo_(
      module,
      'Complete',
      'Recommendation appended: ' + recommendationId
    );

    return {
      recommendationId: recommendationId,
      eventId: eventId
    };

  } catch (error) {
    foError_(module, 'Failure', error);
    throw error;
  }
}

function foAppendSampleRecommendation() {
  return foAppendRecommendationEvent({
    ticker: 'SAMPLE',
    company: 'Sample Company',
    recommendationAction: 'Watch',
    recommendationStatus: 'Proposed',
    recommendationType: 'Initial',
    confidenceScore: 0,
    materialityScore: 0,
    investmentThesis: 'Sample recommendation for service validation.',
    cioNotes: 'Generated by foAppendSampleRecommendation.'
  });
}